### ISSUE TITLE
Increase Google Analytics tracking AMP on DIRECT channel

### ISSUE THREAD

**Issue by hkmgame** [ampproject/amphtml#16566]
Since last May, I'm seing an increase of AMP traffic on the Direct channel of many websites I'm working on.

The increase is follow the decrease on the normal tracking channel of my AMP pages (organic search). I'm trying to figure this out, but, I'm not able to find a decent response or solution.

Any idea on how to deal with that ? What might be the reason ??

Thanks.

See image of the increase and drop of AMP traffic from my direct and organic channels

![](https://i.stack.imgur.com/ydS60.jpg)

**Comment by hkmgame** [comment]
It seems like I'm not the only one facing the same issue : https://www.en.advertisercommunity.com/t5/Google-Analytics-Reports/In-Google-analytics-AMP-Sudden-increase-of-Direct-traffic/m-p/1752963

**Comment by lannka** [comment]
@hkmgame thanks for reporting. The issue is being fixed in Google Search, which will probably land in production soon. /cc @ericfs

**Comment by hkmgame** [comment]
@lannka Thanks for the update. I'm looking forward to see the implementation and the result on Analytics. :)

**Comment by cscheini** [comment]
We (a bigger german publisher) see the same development since mid May 2018, but can't see there was any change or improvement with the possible fix end July.

Chrome went from close to 100% Organic to less than 30%, Direct went up about the same. on Safari, organic is quite stable at high level.

There's other publishers in our group, where status is about the same - change mid may, no improvement since then.

was the problem fixed for you on GA side @hkmgame   ?

we still have millions of chrome users directly typing AMP urls into their phones :)

![image](https://user-images.githubusercontent.com/43581849/46029123-d9977300-c0f2-11e8-96f7-72841392987d.png)

**Comment by cscheini** [comment]
Update on that - we saw a bigger switch back to Organic on Chrome around 2nd of October.

Still 'Direct' is on 20% of Traffic for Chrome (it was close to 0% before that behavior appeared) - so maybe not fully fixed, but looks at least better.

![image](https://user-images.githubusercontent.com/43581849/46940261-97fe4600-d068-11e8-8991-4c3d53e149cb.png)

**Comment by hkmgame** [comment]
@cscheini my issues seems to be resolved. We did implement AMP for all our websites, with a estimated monthly pageviews of 10 Millions. I didn't check directly if the issue was from the browser (chorme) results. I'll try to further investigate.

**Comment by pbazerque** [comment]
could it be some HTTP to HTTPS losing referrals ?

**Comment by cscheini** [comment]
@pbazerque good point..  i think we live in an https-only world here :) - so would suspect this should not be an issue (also after Direct was close to 0% before the tracking bug appeared)
