### ISSUE TITLE
Main AMP script broken in Internet Explorer since latest update.

### ISSUE THREAD

**Issue by SimonHogstromRonbol** [ampproject/amphtml#17505]
## What's the issue?

Hey, i just noticed that all amp components have stopped working in internet explorer, we have around 22 canonical amp websites on different domains, and they all seem to have all had all AMP features disabled just now.

my console on IE says "The object doesn't support the property or method 'assign' on line 519
referring to the file "https://cdn.ampproject.org/v0.js"

## How do we reproduce the issue?

Open any of these sites in Internet explorer:

https://www.chs-container.dk/
http://www.pahavnen.dk/
https://www.damhuskoereskole.dk/

i have around 20 more sites with the same error, every single amp site we have, has this issue.

## What browsers are affected?

This is only an issue in internet explorer

## Which AMP version is affected?

tested in 1533924452420, i'm fairly certain that this is recent.

**Comment by ithinkihaveacat** [comment]
What AMP features have stopped working? Can you provide a bit more detail about how the sites look/behave differently than expected?

I can reproduce a similar error in `v0.js` (which of course should be fixed) via browserstack, but the sites otherwise appear to behave correctly:

![screen shot 2018-08-15 at 2 14 44 pm](https://user-images.githubusercontent.com/51244/44149997-e52880e2-a095-11e8-92ae-7de718df6440.png)

**Comment by SimonHogstromRonbol** [comment]
im seeing this issue with any amp-img tags. no amp tags are display proberly.
![image](https://user-images.githubusercontent.com/32469390/44150501-f317080e-a09f-11e8-8b26-5ea95fb44909.png)

this is ampproject.org in Internet Explorer right now:
![image](https://user-images.githubusercontent.com/32469390/44150541-0cdfdea0-a0a0-11e8-86c4-d2e9f85d9ebb.png)

**Comment by SimonHogstromRonbol** [comment]
to add to the above, i've tested this in IE Edge, 10 and 9, all had the same issues, and i have tested it on 3 different windows machines in the office, windows 8 and windows 10.

**Comment by ithinkihaveacat** [comment]
Sorry, I've been unable to reproduce this, hopefully someone else can. (My test setup: latest Edge at browserstack, using InPrivate mode and with dev-channel both on and off.)

**Comment by aghassemi** [comment]
@jridgewell @prateekbh anything changed with `object.assign` polyfill recently?

**Comment by prateekbh** [comment]
not that i know of

**Comment by aghassemi** [comment]
@SimonHogstromRonbol I can reproduce your issue, amp-tags that are below the fold do not load due to this error in IE11.

@jridgewell The error seems to break runtime lazy-loading, elements above the fold get laidout but nothing below.

**Comment by kevinkassimo** [comment]
Experienced the issue when working on `amp-image-slider`, originally thought it was development only.

**Comment by jridgewell** [comment]
Debugging

**Comment by jridgewell** [comment]
The `values` error is https://github.com/ampproject/amphtml/pull/17408.

**Comment by jridgewell** [comment]
Marking this fixed by https://github.com/ampproject/amphtml/pull/17408.

**Comment by jridgewell** [comment]
We're in the process of releasing a patch. https://github.com/ampproject/amphtml/issues/17515

**Comment by aghassemi** [comment]
Thanks @jridgewell

**Comment by SimonHogstromRonbol** [comment]
Request to reopen this issue.

the fix that was cherry picked in #17515 did not solve this issue.

the IE console log error is:

```
SCRIPT438: Object doesn't support property or method 'assign'
v0.js (519,398)
```
as referenced in #17528

and it makes any AMP site unable to render any amp custom tags, above or below the fold.

i've stitched together a screenshot of how amproject.org renders in IE, but it could be ANY amp site using any amp custom html tags.

![ampproject org](https://user-images.githubusercontent.com/32469390/44195548-a6e47d00-a139-11e8-8f2f-d7303cd7e592.jpg)

i want to stress that his is not an ampproject.org issue, this is any amp site, using amp custom html tags, viewed using Edge, IE 11, 10 or 9.

**Comment by aghassemi** [comment]
reopening, object.assign is still an issue

**Comment by Publimix** [comment]
On further investigation, none of the used components is working on Iphone (Safari browser): amp-video, amp-img, amp-youtube etc. Eg.: [https://publimix.ro/blog](https://publimix.ro/blog) #17547
