### ISSUE TITLE
[Owners] Strange behavior with amp-lightbox[scrollable] > amp-list[hidden]

### ISSUE THREAD

**Issue by ashish-r** [ampproject/amphtml#22525]
## What's the issue?
amp-list is displaying a loader icon above the list, and it goes away when I interact (scroll or tap) with the page.
![Screenshot from 2019-05-28 13-19-32](https://user-images.githubusercontent.com/16723776/58460695-c8a07500-814b-11e9-8662-5101856074c4.png)

This whole content is wrapped in a div and hidden by default and on some action, it appears.
This loader goes away when I interact with the page, and then never comes back again.
Since the [src] is used from `amp-bind-macro` which does not require any API call or anything, so ideally this loader should never appear.

## How do we reproduce the issue?

Sample Code:

        <amp-bind-macro id="getYears" 
        expression="[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15].map(x => 2019- x)">
        </amp-bind-macro>

        <amp-list layout="fixed-height" height="10" [height]="getYears().length * 60" 
        [src]="getYears()" id="year-list" items=".">

            <template type="amp-mustache">
                <div class="years__item" role="button" tabindex="0"
                on="tap:AMP.pushState({year: {{ . }}})">
                    <span> {{.}} </span>
                </div>
            </template>

        </amp-list>

## What browsers are affected?

Google Chrome for mobile and desktop

## Which AMP version is affected?

AMP ⚡ HTML – Version 1905140117570

**Comment by torch2424** [comment]
Triaging to @aghassemi since @cathyxz is out , feel free to re-assign. 😄

**Comment by aghassemi** [comment]
/to @choumx looks related to https://github.com/ampproject/amphtml/pull/22227/files as in this case there is no `src` and the new `return this.scheduleRender_` is not resolving the promise in `layoutCallback` keeping the loader visible.

I believe this got fixed yesterday by a patch https://github.com/ampproject/amphtml/pull/22559 . @ashish-r  can you verify whether this is now fixed in your case?

**Comment by ashish-r** [comment]
> /to @choumx looks related to https://github.com/ampproject/amphtml/pull/22227/files as in this case there is no `src` and the new `return this.scheduleRender_` is not resolving the promise in `layoutCallback` keeping the loader visible.
> 
> I believe this got fixed yesterday by a patch #22559 . @ashish-r can you verify whether this is now fixed in your case?

@aghassemi AMP ⚡ HTML – Version 1905291911450. Still not fixed.

**Comment by choumx** [comment]
@ashish-r Is this a regression or a feature request? Also can you share a live codepen/jsbin URL with an example?

**Comment by ashish-r** [comment]
@choumx 
jsbin Link: https://jsbin.com/muvufoc/edit?html,css,js,output
Here, I have tried to create a minimal representation of the bug.
There are two hidden sections, On clicking `Click Here` You get the first section with a plain amp-list sourced with amp-bind-macro which returns a list. When You click on any of the options, This section hides, and a similar section appears sourced to different amp-bind-macro with a loder.

**Comment by choumx** [comment]
Thanks for the demo. 

Interesting bug. Looks like it's not a regression, but a conflict between amp-lightbox taking ownership of its child amp-list vs. dynamic hide/show behavior on the amp-list via `[hidden]`. 

Resources goes into an infinite layout loop:
1. `[hidden]` change calls mutate (requests measure).
2. On next resources loop, resource is not laid out so it calls measure().
3. measure() -> updateLayoutBox() -> toggleLoading(true), which calls mutate (requests measure).
4. Same resources loop skips layout since it has an owner.
5. Go to step 2.

This means `toggleLoading(true)` is called over and over again.

/cc @jridgewell

**Comment by choumx** [comment]
Here's an even smaller repro:
```html
<!DOCTYPE html>
<html amp lang="en">
   <head>
      <meta charset="utf-8">
      <link rel="canonical" href="self.html" />
      <meta name="viewport" content="width=device-width,minimum-scale=1">
      <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
      <script async src="https://cdn.ampproject.org/v0.js"></script>
      <script async custom-element="amp-bind" src="https://cdn.ampproject.org/v0/amp-bind-0.1.js"></script>
      <script async custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.2.js"></script>
      <script async custom-element="amp-lightbox" src="https://cdn.ampproject.org/v0/amp-lightbox-0.1.js"></script>
      <script async custom-element="amp-list" src="https://cdn.ampproject.org/v0/amp-list-0.1.js"></script>
   </head>
   <body>
      <amp-bind-macro expression="[{'title': 'a'}, {'title': 'b'}, {'title': 'c'}]" id="data" layout=nodisplay></amp-bind-macro>

      <button on="tap:lightbox.open">Open lightbox</button>
      <button on="tap:AMP.setState({src: data()})">Set amp-list[src]</button>

      <amp-lightbox id="lightbox" layout="nodisplay">
         <button on="tap:showMe.show">Show hidden amp-list</button>
         <div id=showMe hidden>
            <p>This was hidden</p>
            <amp-list [height]="src.length * 59" [src]="src" src="list.example.json" height="10" id="list" layout="fixed-height">
               <template type="amp-mustache">
                  {{title}}
               </template>
            </amp-list>
         </div>
      </amp-lightbox>
   </body>
</html>
```

One short-term fix is to revert ownership over children in amp-lightbox[scrollable] while it's opened. 

Enabling layers doesn't fix this yet.

**Comment by choumx** [comment]
@ashish-r A workaround is to avoid hidden children in scrollable amp-lightbox. E.g. remove `scrollable`, or change the height of your "hidden section" to 1px instead of actually hiding it.

**Comment by ashish-r** [comment]
@choumx Thanks. I have removed `scrollable` for now and it is working fine.

**Comment by jridgewell** [comment]
@choumx: I'm not sure I understand your example. What are the steps to reproduce?

**Comment by choumx** [comment]
1. Click "Set amp-list [src]" button
2. Click "Open lightbox" button
3. Click "Show hidden amp-list" button.

Expected: The amp-list's loading indicator is not visible.
Actual: The amp-list's loading indicator is visible.

**Comment by jridgewell** [comment]
Investigating this, we need two actions:

1. Break the `toggleLoading` infinite loop.
   - This can be done with something as simple as early existing if the toggle state is the same.
2. Add a new ownership lifecycle callback for when a previously hidden element becomes visible.
   - This should allow owners like `amp-lightbox` to schedule layout for now-visible elements.
