### ISSUE TITLE
browser back can cause clicks to not working in AMP Cache

### ISSUE THREAD

**Issue by tanakayuki** [ampproject/amphtml#30838]
## What's the issue?

browser back can cause clicks to not working in AMP.
However, origin AMP is fine.

## How do we reproduce the issue?

1. Open Google AMP Cache
2. Make transitions within the site
3. Browser Back to AMP Cache (AMP Viewer)  <- (Click not working here)

## What browsers are affected?

I think it will happen at least if you use safari or chrome on iPhone with OS version 13 or higher.

My Device
- iOS 13.5.1  iphoneSE NG
- iOS 14.1    iphoneSE NG

VM Device(browserstack.com)

- iOS 11 iphoneX  OK
- iOS 12 iphoneXS OK
- iOS 13 iphone8  NG
- iOS 14 iphone11 NG

## Which AMP version is affected?

Version 2010132225002 

## Screen Capture and AMP Cache URL

-<img src="https://user-images.githubusercontent.com/7190554/96957625-1df5d700-1536-11eb-974a-04a9744f9de6.gif" width=500 />
 - https://www.google.com/amp/s/www.ikyu.com/sd/theme/a320701c2/amp/

- <img src="https://user-images.githubusercontent.com/7190554/96957633-23532180-1536-11eb-966a-8505d3c81fe7.gif" width=500 />
 - https://www.google.com/amp/s/akiba-pc.watch.impress.co.jp/docs/sp/1160/581/amp.index.html

- <img src="https://user-images.githubusercontent.com/7190554/96957640-26e6a880-1536-11eb-8c90-8e16ac07a961.gif" width=500 />
 - https://www.google.com/amp/s/www3.nhk.or.jp/nhkworld/en/news/20201023_14/amp.html

**Comment by uskay** [comment]
This seems to be a common issue we are seeing recently. cc/ @nainar 
Reference: https://github.com/ampproject/amphtml/issues/27691#issuecomment-716868604

**Comment by uskay** [comment]
cc/ @flaviori , @choumx and @ericfs
Have you seen this behaviour?

**Comment by ericfs** [comment]
Thanks for the detailed report. I think I was able to reproduce it.

Repro steps:
- Using Safari in iOS Simulator 13.4.1
- Open https://www.google.com/amp/s/akiba-pc.watch.impress.co.jp/docs/sp/1160/581/amp.index.html
- Click the "PC" link
- Navigate back
- Try to click the same "PC" link
  - nothing happens
- Scroll the page up and down
- Try to click the same "PC" link
  - It works

Long press to get a link preview does work:

![Simulator Screen Shot - iPhone 11 - 2020-11-06 at 16 25 59](https://user-images.githubusercontent.com/851850/98416319-da7a8d00-204c-11eb-8b12-7289e6c01614.png)

As does selecting text.

This makes me think we may be hitting a browser bug of some sort.

I am not able to reproduce when using  https://akiba-pc.watch.impress.co.jp/docs/sp/1160/581/amp.index.html
So it does seem to be something about showing the page in the AMP Viewer.

@jridgewell do you have any ideas here? I know Safari had some other scrolling related iframe changes so I'm wondering if this could be somehow related.

**Comment by mauricengo-revolve** [comment]
Wondering if there's any updates on resolving this issue and the one in https://github.com/ampproject/amphtml/issues/27691. This seem to be an issue for all AMP sites. Are these issues top priority?
@flaviori , @choumx and @ericfs

**Comment by ericfs** [comment]
I think @flaviori was looking to get someone to work on #27691.

For this one, I don't have any additional insight. Pinging @jridgewell for thoughts.

**Comment by ericfs** [comment]
I think this is very likely a Safari bug. One thing that may fix it is to programmatically scroll the page. Something like `window.scrollTo(scrollX - 0.1, 0)`.

@dvoytenko, @jridgewell, who would be a good owner for this issue?
Are either of you in contact with Safari for other scrolling issues? It seems like this would be worth reporting.

**Comment by dvoytenko** [comment]
@ericfs Any possibility that this might be some sort of a glasspane in the viewer?

**Comment by ericfs** [comment]
Based on my observations, I don't think it is a glasspane. I can scroll within the iframe and once I scroll, I can click on links.

**Comment by mauricengo-revolve** [comment]
Hi @bartesn, @dvdyakonov, @flaviori , @choumx and @ericfs.

We want to fully launch our AMP site, however we're still seeing the link freezing issue. We observe this issue on other AMP sites as well. I believe It persist on most iPhone devices using Safari.

**Comment by ericfs** [comment]
@jridgewell @samouri Can this issue be reopened? It looks like the problem is happening again. I can reproduce in iOS Simulator 14.4 but not 13.4 with the previous example: https://www.google.com/amp/s/akiba-pc.watch.impress.co.jp/docs/sp/1160/581/amp.index.html

It looks like #31750 is no longer mitigating the issue.

**Comment by ericfs** [comment]
Filed b/191386761 as an internal issue in case there is anything that can be done on the Google side.

**Comment by ericfs** [comment]
It looks like this issue is resolved in iOS 15 which is still in beta.

**Comment by danvuquoc** [comment]
This seems to still be an issue in iOS 15.

**Comment by DavidGonzalez21** [comment]
I can reproduce on IOS 15 google chrome Version 98.0.4758.85

**Comment by Suoakira** [comment]
Was there any resolution on this? We are still seeing this especially click on the organic links then navigiating to dirty amp and then back again to amp.
