### ISSUE TITLE
<amp-iframe> elements must be positioned outside the first 75% of the viewport or 600px from the top (whichever is smaller): 

### ISSUE THREAD

**Issue by rosemaria0996** [ampproject/amphtml#31985]
### The Issue amp-iframe error

<amp-iframe> elements must be positioned outside the first 75% of the viewport or 600px from the top (whichever is smaller):  <amp-iframe width=​"200" height=​"60" sandbox=​"allow-scripts allow-same-origin" layout=​"responsive" frameborder=​"0" src=​"https:​/​/​www.emailmeform.com/​builder/​embed/​1miAfsfG7ddlg84Kq3Z18b" class=​"i-amphtml-element i-amphtml-layout-responsive i-amphtml-layout-size-defined i-amphtml-built i-amphtml-error i-amphtml-layout" i-amphtml-layout=​"responsive" style=​"--loader-delay-offset:​6ms !important;​">​…​</amp-iframe>​ Current position 454 . Min: 600 Positioning rules don't apply for iframes that use `placeholder`.See https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md#iframe-with-placeholder for details.

### How do we reproduce the issue?
The error in the console is like that, when you open the page, it seems normal. 
But if you reload the page with the iframe, the error sometimes will occur.
You can try by pressing Ctrl+R until the page reloaded but if no error you can try reload again.

### What browsers are affected?
I have used Chrome, Mozilla, UC Browser, Microsoft EDGE. All has this bug

### Which AMP version is affected?
Powered by AMP ⚡ HTML – Version 2012301722001 http://194.103.141.38/

**Comment by rosemaria0996** [comment]
this is the page [http://194.103.141.38/daftar](http://194.103.141.38/daftar) that also has the error

**Comment by kristoferbaxter** [comment]
This happens as a result of the `iframe` being in the first 75% of the viewport for certain page resolutions with this document.

<img width="1064" alt="Screen Shot 2021-01-15 at 7 04 25 AM" src="https://user-images.githubusercontent.com/61764/104743247-4ee24400-5700-11eb-8978-60a6b6302f1f.png">

Potential solutions:
1. Use Responsive Design on the document, so the iframe contents appear below the first 75% of the viewport.
2. Replace this `<amp-iframe>` usage with `<amp-form>` since this appears to be an embedded form.

We're unlikely to relax this restriction on iframes in the first 75% of the viewport, since it would lead to a larger number of valid documents that are only iframes to other less optimized experiences.

**Comment by caroqliu** [comment]
Reopening to add some additional information:

I am able to reproduce what @rosemaria0996 is describing on desktop with very large screens. I believe there are two issues going on, the first which [@kristoferbaxter described earlier](https://github.com/ampproject/amphtml/issues/31985#issuecomment-760997498) and should be fixed for devices with very narrow and long viewports.

I believe another issue is for very wide viewports, when the `amp-iframe` _should_ meet the `75%`/`600px` threshold. The example document contains a responsive `amp-carousel` above the responsive `amp-iframe` element throwing the error described. With a 1050x800px viewport, I expect both elements to resolve to a size of `1000x500px`, but when I set a breakpoint on the line which throws the error for `amp-iframe`'s viewport positioning, I see that sometimes it measures the element's `top` as `934px` (> `600px` required), and sometimes it measures it as `434px`. 

This indicates to me both that there is layout shift occurring and a race which throws the error based on if the iframe is measured before or after that shift occurs. Because the discrepancy is exactly `500px`, it's possible that this is related to the `amp-carousel`'s responsive sizing, since it is `500px` tall in this case and above the `amp-iframe`. 

A few additional things you could do to help with this document:
- I noticed the document is not valid AMP and does not import all the extensions in the `<head>`. Making sure your document conforms to the AMP validator is one good way to help mitigate this issue and stabilize element sizing on the page.
- The document imports `amp-carousel` version `0.1`, and will likely benefit from upgrading to `0.2`.

What AMP should do to help:
- Investigate layout shift in amp-carousel 0.1.
- Make amp-carousel 0.2 more easily accessible as a preferred alternative.

**Comment by rosemaria0996** [comment]
@kristoferbaxter Thanks for the solution, but i tried that and don't know if the amp-form can be used for the embedded form. And I can not change the embedded form with manual form design.

@caroqliu Thanks for the solution, I'll try to put the import extension to the head and check the results

**Comment by rosemaria0996** [comment]
@caroqliu I have applied  and put the import extension to the head. And it become better, but looks like sometimes it still occur the bug, maybe about 1/15 chance in my case.

**Comment by caroqliu** [comment]
@rosemaria0996 Have you tried upgrading to `amp-carousel` version `0.2`?
