### ISSUE TITLE
Support for measuring Interaction to Next Paint (INP)

### ISSUE THREAD

**Issue by pierres** [ampproject/amphtml#38470]
### Description

In order to be able to track the new web vital metric [Interaction to Next Paint (INP)](https://web.dev/inp/), it would be great if it could be measured and made available as variable substitution similar to e.g. [${cumulativeLayoutShift}](https://github.com/ampproject/amphtml/blob/main/docs/spec/amp-var-substitutions.md#performance).

### Alternatives Considered

We currently use `<amp-analytics>` on pages meant for Google's AMP cache, as well on their canonical counterparts. This also means custom code that e.g. uses the [web-vitals](https://github.com/GoogleChrome/web-vitals) library cannot be utilized.

**Comment by erwinmombay** [comment]
Fixed by https://github.com/ampproject/amphtml/pull/39345 , it is currently under an experiment guard as we need to confirm the data we are transmitting

**Comment by eduardcotmrf** [comment]
Do you have any forecast of when it will be available without the experiment guard?

**Comment by powerivq** [comment]
@eduardcotmrf It has already been useable by all.

**Comment by eduardcotmrf** [comment]
I tested it last week and it was still opn experiment so the real traffic was not working for it: https://github.com/ampproject/amphtml/blob/main/src/service/performance-impl.js#L240 The line of code seems like is still the same.

Maybe the experiment has been activated for some traffic? It wasn't for me from spain

**Comment by powerivq** [comment]
@eduardcotmrf The experiment was launched to 100% traffic (https://github.com/ampproject/amphtml/blob/ca74ac5e3726ebecfb56927ad40ccf0405ce1a76/build-system/global-configs/prod-config.json#L19)

Can you show an example page to see what went wrong?

**Comment by eduardcotmrf** [comment]
Tested it and it works fine now, thanks!

**Comment by eduardcotmrf** [comment]
After some months of storing the INP data in a lot of different clients and urls we don't understand the results. We allways get a INP of 40ms no matter the web page, device, etc,.

If tested thi fiddle with a basic AMP HTML: `https://jsfiddle.net/aL48rxbf/` and I also get a 40 ms, like all the amp pages i'vw tested. This raises a concern, is this value correct? All AMP pages report 40ms on INP or there is some bug?

**Comment by powerivq** [comment]
@eduardcotmrf We chose the INP_REPORTING_THRESHOLD to be 40ms. see the comments here https://github.com/GoogleChrome/web-vitals/blob/main/src/onINP.ts#L126

Excessively low number might be a flake and so we choose to report them at 40ms.

**Comment by eduardcotmrf** [comment]
Event with that threshold the results seem incorrect. We have analytics for milions of URLS and most of them, in AMP, are reporting 40ms but in search console or page speed are reporting different numbers.

We are getting the INP like this: 

```js
    "webVitalsTimer": {
      "on": "timer",
      "timerSpec": {
        "interval": 10,
        "maxTimerLength": 1800
      },
      "request": "event",
      "vars": {
        "eventId": "timer",
        "pageViewId64": "PAGE_VIEW_ID_64",
        "version": 0.2
      },
      "extraUrlParams": {
        "ac": "${accountId}",
...
        "lcp": "${largestContentfulPaint}",
        "fcp": "${firstContentfulPaint}",
        "inp": "${interactionToNextPaint}",
...
      }
    },

    "webVitalsEnd": {
      "on": "visible",
      "request": "event",
      "visibilitySpec": {
        "reportWhen": "documentExit"
      },
      "vars": {
        "eventId": "timer",
        "pageViewId64": "PAGE_VIEW_ID_64",
        "version": 0.2
      },
      "extraUrlParams": {
        "ac": "${accountId}",
....
        "lcp": "${largestContentfulPaint}",
        "fcp": "${firstContentfulPaint}",
        "inp": "${interactionToNextPaint}",
...
      }
    },
```

For example in this url: https://bolavip.com/amp/uefa/11-equipos-importantes-de-Europa-que-nunca-ganaron-la-Champions-League-20220215-0015.html

We are getting 40ms for all visits on real data but on page speed we are gettin 637ms... so somewhere there is something wrong.

![Captura de pantalla 2024-02-27 a les 9 42 27](https://github.com/ampproject/amphtml/assets/23262331/d10aa8bb-c7c0-4086-a637-b11e87e43cd5)

https://pagespeed.web.dev/analysis/https-bolavip-com-amp-uefa-11-equipos-importantes-de-Europa-que-nunca-ganaron-la-Champions-League-20220215-0015-html/ngvs1vtw8q?form_factor=mobile
