### ISSUE TITLE
Ads in Web Stories not triggering 

### ISSUE THREAD

**Issue by LuckynaSan** [ampproject/amphtml#38552]
### Description

As [originally reported](https://wordpress.org/support/topic/web-story-ads-not-clickable) in the Web Stories support forum, the ads in a Web Story are not opening the ad. Could you please check if there is anything from the AMP side that could be affecting this? Thank you! 

Issue occurs on the following:

Browser: Chrome 107.0.5304.110 / Device: Android Iqoo z5
Browser: Safari 16.1.1 / Device: iPhone 13

Current behavior: Clicking on an ad inside a Web Story is not triggering the ad to open.
Expected Behavior: Ads on Web Stories should trigger.

Recording of what happens when clicking "Open" on the ad: 

https://user-images.githubusercontent.com/66372350/202490227-8886fd9f-8e58-44ac-8f4d-cee90399d216.mov

### Reproduction Steps

1. View [Web Story](https://equicity.in/web-stories/face-par-pimples-kyu-hote-hai-in-hindi/) on mobile device
2. When ad appears, click on Open or the ad.

### Browser(s) Affected

Chrome, Safari

### OS(s) Affected

Android, iPhone

### AMP Version Affected

2.3.0

**Comment by Mission-Impossible0** [comment]
This is the link of web story
[https://sarkariexampur.in/web-stories/loan-process-on-banks/](https://sarkariexampur.in/web-stories/loan-process-on-banks/)

**Comment by ShubhamChoudharyShubh** [comment]
same this problem in my web stories ads are visible but not clickable

**Comment by gulabbisht** [comment]
Yes, can verify that this issue coming up for the last few weeks. None of the ad links are clickable and it goes to the next screen.
![Screenshot 2022-12-16 at 2 56 03 PM](https://user-images.githubusercontent.com/2059780/208040625-fe8dd735-8f1a-40cc-8196-642ec7855066.png)

**Comment by vikas5154** [comment]
Ads are not clickable in webstory.this is screen recording [](https://www.veed.io/view/6b614e13-7452-4c0d-92dc-1ce03f070ac2?)panel=share .this is web story link [](https://ayodhyanagar.com/web-stories/argentina-defeats-croatia-3-0-in-the-world-cup-final-and-lionel-messi-declares-it-to-be-his-final-world-cup-game-ever/) .This thing is happen with every story.Please help me to solve this issue.

**Comment by avidbe** [comment]
same issue did anybody fix the issue , please somebody help

**Comment by vanitascorner** [comment]
Even I am facing this problem. The ads on my webstories are not clickable. Has anyone fixed this issue? Please help

**Comment by newmuis** [comment]
This is still being investigated; we will update the issue as soon as we've identified a fix!

**Comment by mszylkowski** [comment]
Found a fix. After fixing [Make grid-layer content not click shield other elements](https://github.com/ampproject/amphtml/pull/38377) the ad container need `pointer-events: all`. I'll send a PR soon.

**Comment by vanitascorner** [comment]
Is the problem fixed ? I am still not able to click on the ads.

Regards

**Comment by mszylkowski** [comment]
We've merged the fix, which means the next [release](https://github.com/ampproject/amphtml/blob/main/docs/release-schedule.md#weekly) will contain the fix.

**Comment by vanitascorner** [comment]
Great, thanks!

**Comment by aabidgh** [comment]
I'm facing the same issue from last several days, @mszylkowski is this fix will automatically get fixed with an update with web stories plugin or do we need to do something in our wordpress, please let me know

**Comment by mszylkowski** [comment]
It will get fixed automatically in the next release of AMP

**Comment by bestsaller** [comment]
When next realised published

**Comment by newmuis** [comment]
I think it will go out January 3 or 4.

@mszylkowski and @erwinmombay can you work together to ensure this goes out (and gets cherry picked if needed)?

**Comment by bestsaller** [comment]
Sir, still not get solution of web story clickable
And not realse updated version..

**Comment by newmuis** [comment]
@estherkim do you know the status/ETA of the new stable?

**Comment by estherkim** [comment]
The new stable `2212151632002` went out yesterday around 4:30pm ET. It includes https://github.com/ampproject/amphtml/pull/38604

**Comment by newmuis** [comment]
@mszylkowski can you investigate whether you can still reproduce in the new stable?

**Comment by newmuis** [comment]
@mszylkowski or @erwinmombay can you investigate whether you can still reproduce in the new stable?

**Comment by mszylkowski** [comment]
On the story https://ayodhyanagar.com/web-stories/argentina-defeats-croatia-3-0-in-the-world-cup-final-and-lionel-messi-declares-it-to-be-his-final-world-cup-game-ever/ I can click on the button and it takes me to the ad (this is the story that we previously used to debug this so it was broken before the fix). @bestsaller Is there a story you've been able to reproduce this issue after the stable release? If not, we can re-close.

Note when hovering over the button, Chrome displays the address of the link (which means the link is clickable):

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/22420856/210831441-650f0173-a901-4a12-a4ea-4c3e82a93397.png">

**Comment by vanitascorner** [comment]
Yes.. The ads have started triggering. Thank you.

**Comment by Aditya-Saini3** [comment]
The ads are clickable on desktop but they are still not clickable on mobile.

**Comment by newmuis** [comment]
@Aditya-Saini3 do you have an example URL?  I am able to click the ads on mobile on the example that @mszylkowski shared above.

Also, if you've run into this issue before, be sure that you're testing in an incognito/private window to ensure that you don't have the old problematic version cached

**Comment by Aditya-Saini3** [comment]
Yes thankyou I also ran into this problem before and now opening the example link in incognito solved this problem.
